### ISSUE TITLE
No windows extension

### ISSUE THREAD

**Issue by ogimgio** [qdrant/qdrant_demo#12]
Thanks for this great demo!

I suggest you also add win32 torch wheel, as currently is missing. How do i run poetry install on windows machine else?
torch = [
    {url="https://download.pytorch.org/whl/cpu/torch-2.0.1%2Bcpu-cp311-cp311-win_amd64.whl", markers = "python_version == '3.11' and sys_platform == 'win32' and platform_machine == 'AMD64'"},
]

**Comment by generall** [comment]
New version doesn't use pytorch anymore
