### ISSUE TITLE
Mismatching names

### ISSUE THREAD

**Issue by a0m0rajab** [qdrant/qdrant_demo#17]
While following the https://qdrant.tech/documentation/tutorials/neural-search/ tutorial, I thought that having the data preparation in the same Git folder would be better, and I noticed the next: 

In this file the user is asked to have two files that the project does not find due the next: 
https://github.com/qdrant/qdrant_demo/blob/fd3ab3d3aa6ff4ee32b8359c14e6f72f951f96f4/README.md?plain=1#L30

the code in the project is looking for different file names 
https://github.com/qdrant/qdrant_demo/blob/fd3ab3d3aa6ff4ee32b8359c14e6f72f951f96f4/qdrant_demo/init_collection_startups.py#L8-L12

**Comment by joein** [comment]
Hi, thanks for pointing it out!

These variables were actually obsolete and were not used, however the issue has already been resolved.
