### ISSUE TITLE
`startups.sqlite3` missing

### ISSUE THREAD

**Issue by aseifert** [qdrant/qdrant_demo#2]
When trying to launch the demo as described, the following issue will arise:

`web_1     | sqlite3.OperationalError: unable to open database file`

I looked around in the repo and instructions and Google Colab file, but didn't find any place where that sqlite3 file is created, so I guess you just forgot to include the proper instructions.

**Comment by generall** [comment]
Hi, `startups.sqlite3` is generated with `python -m qdrant_demo.init_text_search_index`. The instruction order is indeed wrong, thanks for reporting this!
